# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://yinjiahui.cn/"
title = "Jane - A super concise theme for Hugo"
theme = "ananke"